package br.com.code.ws.jaxws.samples.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-02-16T18:33:54.149-02:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", name = "CalculatorWs")
@XmlSeeAlso({ObjectFactory.class})
public interface CalculatorWs {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/divideRequest", output = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/divideResponse")
    @RequestWrapper(localName = "divide", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.Divide")
    @WebMethod
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.DivideResponse")
    public java.lang.Double divide(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/addRequest", output = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/addResponse")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.AddResponse")
    public java.lang.Integer add(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/subtractRequest", output = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/subtractResponse")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.Subtract")
    @WebMethod
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.SubtractResponse")
    public java.lang.Integer subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/multiplyRequest", output = "http://ws.code.com.br/jaxws/samples/v1/CalculatorWs/multiplyResponse")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.Multiply")
    @WebMethod
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://ws.code.com.br/jaxws/samples/v1", className = "br.com.code.ws.jaxws.samples.v1.MultiplyResponse")
    public java.lang.Integer multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );
}
